language: java
install: TERM=dumb gradle setupCIWorkspace
script: TERM=dumb gradle build
after_success:
- TERM=dumb gradle uploadArchives
notifications:
  webhooks:
  - http://n.tkte.ch/h/2127/m63lw4PlbNcGxQwP0MYvaXWq
env:
  global:
  - secure: CdgHXhywMxVLcKUPwzsY51WUP1nvkUwNQbkn790SAL3zpuz9nJ15NoGU0XMdhkiD6gYq3zqVFjwBE+WsAsqogYtmx0NygtiqyV7m1j1X3B+1/5uQHudmaqJATuVTMTpCV5ZXKl0nM2XyJbny2nNmhjTQUjUoEgDCGgIMi27OTSg=
  - secure: VyP93nrx6Cg5r1Va/OoT6v+Wgg82GST1Wt47YmitzjjbKHDeDmHbFGVChGakQAPgbAaUHec6i+gihE1sthB7Hmc7muz6nU+az56i0ORxKoMDkkCDMua/bNGiCm5AjNtXpogSgRi2xnKEfWyI38LLJhdL/APdg4yjQxFRy7gUyII=
  - secure: B4ak1uuGLuLND+Fq12jJ539k1bGgySSPKuCXLsYOi5CbBKGVnBA5pEjWYFlhuTy1qmWsocsWRv0qv3SEH9bN3VIylfAwHK81qK0MJbx6AtBrL5bM77r7NHmN+POj35hjvBgWp/1SJyj9SSYZhlWA5SgjLlh3/ULFLGKDZvmyR0Q=
